url: https://kas-hellas.com/
baseurl: https://kas-hellas.com/

# Site settings
title: K.A.S.
email: kas.mondo@outlook.com
description: "KAS in a B2B coffee trading firm, respesenting Mondo in Greece."


# Team names, titles and social links
people:
- name: Stelios Koulaxis
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/SKoulaxis
    - title: envelope
      url: info@kas-hellas.com 
    - title: linkedin
      url: https://www.linkedin.com/in/stylianos-koulaxis-074738176/ 

- name: Dimitris Arvanitidis
  pic: 2
  position: Co-founder
  social:
    - title: twitter
      url: https://twitter.com/dmarv97?fbclid=IwAR2KKG-34ZEkORkl7hMg0TSiooLUwa3X7rIbrFhHdxU7x7-XZcWJfQwvqbg
    - title: envelope
      url: dimitris@kas-hellas.com
    - title: linkedin
      url: https://www.linkedin.com/in/dimitrios-arvanitidis-7859a018a/

- name: Nikolas Stamatopoulos
  pic: 3
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: envelope
      url: nikolas.stamato@gmail.com
    - title: linkedin
      url: https://www.linkedin.com/in/nikolaos-stamatopoulos-b717a6133/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/kas_hellas/
  - title: linkedin
    url: https://www.linkedin.com/company/k-a-s-private-company
  - title: github
    url: https://github.com/KAS-mondo/kas-mondo.github.io

# Postal address (add as many lines as necessary)
address:
  - line: Profitou Ilia 21 & Karavageli 2
  - line: Pylaia, Thessaloniki, Greece, 55535
# Build settings
markdown: kramdown
permalink: pretty
