url: https://kas-hellas.com/
baseurl: https://kas-hellas.com/

# Site settings
title: K.A.S.
email: kas.mondo@outlook.com
description: "KAS in a B2B coffee trading firm, respesenting Mondo in Greece."


# Team names, titles and social links
people:
- name: Stelios Koulaxis
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Dimitris Arvanitidis
  pic: 2
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: email
      url: #
    - title: linkedin
      url: #

- name: Nikolas Stamatopoulos
  pic: 3
  position: Co-founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: github
    url: https://github.com/KAS-mondo/kas-mondo.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
